"""add_caching_columns

Revision ID: 39aff0cdf14e
Revises: 001_add_stock_daily_prices
Create Date: 2026-01-19 13:11:24.240293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39aff0cdf14e'
down_revision: Union[str, None] = '001_add_stock_daily_prices'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_companies', sa.Column('charter_capital', sa.Float(), nullable=True))
    op.add_column('stock_companies', sa.Column('pe_ratio', sa.Float(), nullable=True))
    op.add_column('stock_companies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_companies', 'updated_at')
    op.drop_column('stock_companies', 'pe_ratio')
    op.drop_column('stock_companies', 'charter_capital')
    # ### end Alembic commands ###
