"""add exchange to stock_companies

Revision ID: 03b7a32c91f5
Revises: 9c7a3e4f5b2d
Create Date: 2026-01-28 15:07:33.741174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b7a32c91f5'
down_revision: Union[str, None] = '9c7a3e4f5b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_companies', sa.Column('exchange', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_companies', 'exchange')
    # ### end Alembic commands ###
