"""add_stock_indices

Revision ID: 1a5fe5192058
Revises: 39aff0cdf14e
Create Date: 2026-01-20 17:13:09.356333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5fe5192058'
down_revision: Union[str, None] = '39aff0cdf14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_indices_id'), 'stock_indices', ['id'], unique=False)
    op.create_index(op.f('ix_stock_indices_symbol'), 'stock_indices', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_indices_symbol'), table_name='stock_indices')
    op.drop_index(op.f('ix_stock_indices_id'), table_name='stock_indices')
    op.drop_table('stock_indices')
    # ### end Alembic commands ###
