"""Shared LLM services."""

from .tasks import (
    DEFAULT_LLM_TASK_KEY,
    NEWS_ARTICLE_CLASSIFICATION_TASK,
    NEWS_ARTICLE_SUMMARY_TASK,
    NEWS_BLOCKED_LABEL_COMPILATION_TASK,
    POSITION_IMAGE_EXTRACTION_TASK,
    POSITION_TABLE_EXTRACTION_TASK,
)

__all__ = [
    "DEFAULT_LLM_TASK_KEY",
    "POSITION_IMAGE_EXTRACTION_TASK",
    "POSITION_TABLE_EXTRACTION_TASK",
    "NEWS_ARTICLE_SUMMARY_TASK",
    "NEWS_ARTICLE_CLASSIFICATION_TASK",
    "NEWS_BLOCKED_LABEL_COMPILATION_TASK",
]
