DEFAULT_LLM_TASK_KEY = "default"
POSITION_IMAGE_EXTRACTION_TASK = "position_image_extraction"
POSITION_TABLE_EXTRACTION_TASK = "position_table_extraction"


__all__ = [
    "DEFAULT_LLM_TASK_KEY",
    "POSITION_IMAGE_EXTRACTION_TASK",
    "POSITION_TABLE_EXTRACTION_TASK",
]
