DEFAULT_LLM_TASK_KEY = "default"
POSITION_IMAGE_EXTRACTION_TASK = "position_image_extraction"
POSITION_TABLE_EXTRACTION_TASK = "position_table_extraction"
NEWS_ARTICLE_SUMMARY_TASK = "news_article_summary"
NEWS_ARTICLE_CLASSIFICATION_TASK = "news_article_classification"
NEWS_ARTICLE_DISCUSSION_TASK = "news_article_discussion"
NEWS_ARTICLE_DISCUSSION_DECISION_TASK = "news_article_discussion_decision"
NEWS_ARTICLE_DISCUSSION_QUERY_TASK = "news_article_discussion_query"
NEWS_BLOCKED_LABEL_COMPILATION_TASK = "news_blocked_label_compilation"


__all__ = [
    "DEFAULT_LLM_TASK_KEY",
    "POSITION_IMAGE_EXTRACTION_TASK",
    "POSITION_TABLE_EXTRACTION_TASK",
    "NEWS_ARTICLE_SUMMARY_TASK",
    "NEWS_ARTICLE_CLASSIFICATION_TASK",
    "NEWS_ARTICLE_DISCUSSION_TASK",
    "NEWS_ARTICLE_DISCUSSION_DECISION_TASK",
    "NEWS_ARTICLE_DISCUSSION_QUERY_TASK",
    "NEWS_BLOCKED_LABEL_COMPILATION_TASK",
]
