DEFAULT_LLM_TASK_KEY = "default"
POSITION_IMAGE_EXTRACTION_TASK = "position_image_extraction"
POSITION_TABLE_EXTRACTION_TASK = "position_table_extraction"
NEWS_ARTICLE_SUMMARY_TASK = "news_article_summary"
NEWS_ARTICLE_CLASSIFICATION_TASK = "news_article_classification"
NEWS_BLOCKED_LABEL_COMPILATION_TASK = "news_blocked_label_compilation"


__all__ = [
    "DEFAULT_LLM_TASK_KEY",
    "POSITION_IMAGE_EXTRACTION_TASK",
    "POSITION_TABLE_EXTRACTION_TASK",
    "NEWS_ARTICLE_SUMMARY_TASK",
    "NEWS_ARTICLE_CLASSIFICATION_TASK",
    "NEWS_BLOCKED_LABEL_COMPILATION_TASK",
]
